### ISSUE TITLE
Update to minecraft 1.18

### ISSUE THREAD

**Issue by lerfis** [nok-ko/keepinventory-command#1]
Hi, can you please update this mod to minecraft 1.18 ?

- Mod 'KeepInventory Command' (keepinventory-command) 0.5.1 requires version 1.17.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.18!

Cheers

**Comment by nok-ko** [comment]
Winter break is coming up, so I'll consider it :)

**Comment by lerfis** [comment]
Thanks a bunch, I would really appreciate it 👍

**Comment by nok-ko** [comment]
@lerfis Please give [this release](https://github.com/nok-ko/keepinventory-command/releases/tag/v0.5.2-1.18.x) a test, if it works on multiplayer then I'll close the issue, job done. Depends on the latest Fabric API/Fabric Loader.

**Comment by lerfis** [comment]
Looks like it's working as expected, thanks man!
